export default {
  SIGNIN: "Signin",
  SIGNUP: "Signup",
  FORGOTPASSWORD: "ForgotPassword",
  HOME: "Home",
  CODEVERIFICATION: "CodeVerification",
  CHANGEPASSWORD: "ChangePassword",
  TABROUTES:'TabRoutes',
  HOME:'Home',
  NEARBY:'NearBy',
  BOOKING:'Booking',
  PROFILE:'Profile',
  NOTIFICATION:'Notification',
  NAILSALON:'NailSalon',
  HAIRSALON:'HairSalon',
  MAKEUP:'Makeup',
  SKINCARE:"SkinCare",
  SPA:'Spa',
  HOMESERVICE:'HomeService'
};
